<div class="mask">
    <div class="chooseStoreWrapper">
        <img class="icon_chooseStore" src="/static/images/u/icon_choseStore.png" alt="">
        <div class="chooseStore">
            <center>
                <h2>请选择附近实体店</h2>
                <div id="crm_store">
                <!--
                    <label for="store_CBD" class="store">北京CBD直营店</label>
                    <input id="store_CBD" type="radio" name="store" value="北京CBD直营店">
                    <label for="store_fuchengmen" class="store">北京阜成门金牌店</label>
                    <input id="store_fuchengmen" type="radio" name="store" value="北京CBD直营店">
                    <label for="store_sanlitun" class="store">北京三里屯金牌店</label>
                    <input id="store_sanlitun" type="radio" name="store" value="北京CBD直营店">
                -->
                </div>
                <button class="confirmStore">确定</button>
            </center>
        </div>
        <div class="chooseStoreSucceed">
            <center>
                <div><img class="left" src="/static/images/u/woman_chooseStoreSucceed.png" alt="">
                <h2 class="chooseStoreSucceed_text right">恭喜您！提交成功！</h2></div>
                <div class="clear"></div>
                <p>爱情顾问会尽快联系您，您也可以拨打<br><br>幸福热线：<span>400-8191-521</span>进行咨询</p>
                <a class="back" href="/u/index">返回</a>
            </center>
        </div>
    </div>
</div>
