<div class="qa">
    <img src="/static/images/u/qa.png">
</div>
<div class="title_headerWrapper" id="fixed_header">
    <div class="title_header">
        <img src="/static/images/u/headline.png" alt="" class="left">
        <span id="current_city" class="left btn_citySelect" style="background:url('/static/images/u/area_arrow.png') no-repeat center right;padding-right:32px;">&middot;<?php echo $current_city_data['city_name']; ?></span>
        <span class="right" style="background:url('/static/images/u/hotline_heart.png') no-repeat center left;padding-left:25px;">幸福热线：400-8191-521</span>
    </div>
</div>
