<?php
Html::render($this, 'u/header.phtml');
?>
    <body id="index">
        <div class="wrapper">
<?php
Html::render($this, 'u/service.phtml');
?>
            <div class="content">
                <!-- 实体店列表页内容开始 -->
                <div class="list_manWrapper">
<?php
if (is_array($list_data) && count($list_data) > 0)
{
    foreach ($list_data as $dt)
    {
?>
                    <div class="eachmanWrapper">
                        <a href="/u/storedetail?sid=<?php echo $dt['id']; ?>">
                            <div class="storeImgWrapper left">
                                <img src="/f/p?n=<?php echo $dt['shop_pic']; ?>" alt="" class=" each_head">
                                <!-- center>
                                    <div class="location">
                                        <img src="/static/images/u/location.png" alt="">
                                        <span>9.2km</span>
                                    </div>
                                </center -->
                            </div>
                            <div class="right eachman_content">
                                <div class="row1">
                                    <span class="name"><?php echo $store_base_info[$dt['groupId']]['groupName']; ?></span>
                                </div>
                                <div class="row2">
                                </div>
                                <div class="row3">
                                    <p>
                                        <span>地址：</span>
<?php
    echo $dt['shop_addr'];
?>
                                    </p>
                                </div>
                            </div>
                        </a>
                        <div class="clear"></div>
                        <div class="line_eachman"></div>
                    </div>
<?php
    }
}
else
{
    Html::render($this, 'u/no_result.phtml');
}
?>
                </div>
                <!-- 实体店列表页内容结束 -->
            </div>
<?php
Html::render($this, 'u/nav_footer.phtml', array('nav' => 'store'));
?>            
        </div>
<?php
Html::render($this, 'u/city.phtml', array('city' => array()));
?>
    </body>
<?php
Html::render($this, 'u/footer.phtml');
?>
