<div class="header">
	<div class="headerTitle left">
		<h1>百合实体店</h1>
		<h3>后台管理系统</h3>
	</div>
	<p class="right headerInfoContainer">
	   
	   <!-- 
		<span class="headerInfotype1"><em>2014</em>年<em>11</em>月<em>27</em>日</span>
		<span class="headerInfotype1">14:10:10</span>
		<span class="headerInfotype1">
		<span class="headerInfotype1">星期<em>四</em></span>
		-->
		
		<span class="headerInfotype2" style="margin-right:50px;">当前用户登录名：<em>admin</em></span>
		<!-- 
		<a>修改密码</a>
		<a>退出</a>
		 -->
	</p>
	<div class="clear"></div>
</div>