<div class="sidebar left">
	<p>信息管理</p>
	<ul>
		<li><a style="background:url('/static/images/back/icon_sidebar1.png') no-repeat 0% 50%" href="/back/member">会员</a></li>
		<li><a style="background:url('/static/images/back/icon_sidebar2.png') no-repeat 0% 50%" href="/back/shop">实体店</a></li>
		<li><a style="background:url('/static/images/back/icon_sidebar3.png') no-repeat 0% 50%" href="/back/case">成功案例</a></li>
		<!-- 
		<li><a style="background:url('/static/images/back/icon_sidebar4.png') no-repeat 0% 50%" href="##">爱情顾问</a></li>
		 -->
		<li><a style="background:url('/static/images/back/icon_sidebar5.png') no-repeat 0% 50%" href="/back/act">活动</a></li>
		<!-- 
		<li><a style="background:url('/static/images/back/icon_sidebar6.png') no-repeat 0% 50%" href="##">媒体报道</a></li>
		 -->
	</ul>
	<p class="version">
		<span>版本 V0.1</span>
	</p>
</div>
